CREATE DATABASE IF NOT EXISTS mydb;

USE mydb;

CREATE USER IF NOT EXISTS 'myuser'@'%' IDENTIFIED BY 'mypassword';

GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'127.0.0.1' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;